In [29]:
# This code was taken from Ryan & Matt Data Science 
import seaborn as sns
import pandas as pd

In [30]:
healthexp = sns.load_dataset('healthexp')

In [31]:
healthexp.tail()

     Year        Country  Spending_USD  Life_Expectancy
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

In [32]:
# Debido a que hay una variable categórica 'Country' hay que crear nuevas variables dummies para el analisis
healthexp = pd.get_dummies(healthexp)

In [33]:
healthexp.tail()

,Year,Spending_USD,Life_Expectancy,Country_Canada,Country_France,Country_Germany,Country_Great Britain,Country_Japan,Country_USA
269,2020,6938.983,81.1,False,False,True,False,False,False
270,2020,5468.418,82.3,False,True,False,False,False,False
271,2020,5018.700,80.4,False,False,False,True,False,False
272,2020,4665.641,84.7,False,False,False,False,True,False
273,2020,11859.179,77.0,False,False,False,False,False,True

In [34]:
# Estos son todos menos 'Life_Expectancy' porque queremos predecir con base en el resto de los datos la expectativa de vida
X = healthexp.drop(['Life_Expectancy'],axis=1)

y = healthexp['Life_Expectancy']

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=54)

In [37]:
from sklearn.ensemble import RandomForestRegressor

In [38]:
rfr = RandomForestRegressor(random_state=34)

In [39]:
rfr.fit(X_train,y_train)

RandomForestRegressor(random_state=34)

In [40]:
y_pred = rfr.predict(X_test)

In [41]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [42]:
mean_absolute_error(y_test,y_pred)

0.3115454545454368

In [43]:
mean_squared_error(y_test,y_pred)

0.15524932727271845

In [44]:
r2_score(y_test,y_pred)

0.9836312857564109

In [45]:
import optuna

In [46]:
from sklearn.model_selection import cross_val_score

In [47]:
def objective(trial):
    n_estimators = trial.suggest_int('n_estimators',100,1000)
    max_depth = trial.suggest_int('max_depth',10,50)
    min_samples_split = trial.suggest_int('min_samples_split',2,32)
    min_samples_leaf = trial.suggest_int('min_samples_leaf',1,32)

    model = RandomForestRegressor(n_estimators=n_estimators,
                                  max_depth=max_depth,
                                  min_samples_split=min_samples_split,
                                  min_samples_leaf=min_samples_leaf)
    score = cross_val_score(model,X_train,y_train,cv=5,scoring='neg_mean_squared_error',n_jobs=-1).mean()
    return score

In [48]:
study = optuna.create_study(direction='maximize',sampler=optuna.samplers.RandomSampler(seed=42))

[I 2026-06-02 21:55:35,228] A new study created in memory with name: no-name-92bb81e3-685f-4cde-a73e-c7fd040ac80c

In [49]:
study.optimize(objective,n_trials=200)

[I 2026-06-02 21:55:37,263] Trial 0 finished with value: -2.3128756957884375 and parameters: {'n_estimators': 437, 'max_depth': 48, 'min_samples_split': 24, 'min_samples_leaf': 20}. Best is trial 0 with value: -2.3128756957884375.
[I 2026-06-02 21:55:38,850] Trial 1 finished with value: -2.8993306860968433 and parameters: {'n_estimators': 240, 'max_depth': 16, 'min_samples_split': 3, 'min_samples_leaf': 28}. Best is trial 0 with value: -2.3128756957884375.
[I 2026-06-02 21:55:40,578] Trial 2 finished with value: -3.3568205475025734 and parameters: {'n_estimators': 641, 'max_depth': 39, 'min_samples_split': 2, 'min_samples_leaf': 32}. Best is trial 0 with value: -2.3128756957884375.
[I 2026-06-02 21:55:42,276] Trial 3 finished with value: -1.0176866156267157 and parameters: {'n_estimators': 850, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 6}. Best is trial 3 with value: -1.0176866156267157.
[I 2026-06-02 21:55:42,464] Trial 4 finished with value: -1.5669691458421142 and parameters: {'n_estimators': 374, 'max_depth': 31, 'min_samples_split': 15, 'min_samples_leaf': 10}. Best is trial 3 with value: -1.0176866156267157.
[I 2026-06-02 21:55:42,774] Trial 5 finished with value: -1.7883669216794122 and parameters: {'n_estimators': 651, 'max_depth': 15, 'min_samples_split': 11, 'min_samples_leaf': 12}. Best is trial 3 with value: -1.0176866156267157.
[I 2026-06-02 21:55:43,007] Trial 6 finished with value: -2.2053409915133995 and parameters: {'n_estimators': 510, 'max_depth': 42, 'min_samples_split': 8, 'min_samples_leaf': 17}. Best is trial 3 with value: -1.0176866156267157.
[I 2026-06-02 21:55:43,294] Trial 7 finished with value: -1.1254780626668444 and parameters: {'n_estimators': 633, 'max_depth': 11, 'min_samples_split': 20, 'min_samples_leaf': 6}. Best is trial 3 with value: -1.0176866156267157.
[I 2026-06-02 21:55:43,379] Trial 8 finished with value: -2.6824297859660917 and parameters: {'n_estimators': 158, 'max_depth': 48, 'min_samples_split': 31, 'min_samples_leaf': 26}. Best is trial 3 with value: -1.0176866156267157.
[I 2026-06-02 21:55:43,557] Trial 9 finished with value: -2.071032034206092 and parameters: {'n_estimators': 374, 'max_depth': 14, 'min_samples_split': 23, 'min_samples_leaf': 15}. Best is trial 3 with value: -1.0176866156267157.
[I 2026-06-02 21:55:43,656] Trial 10 finished with value: -3.1807387437168035 and parameters: {'n_estimators': 209, 'max_depth': 30, 'min_samples_split': 3, 'min_samples_leaf': 30}. Best is trial 3 with value: -1.0176866156267157.
[I 2026-06-02 21:55:43,797] Trial 11 finished with value: -2.1921665587526635 and parameters: {'n_estimators': 333, 'max_depth': 37, 'min_samples_split': 11, 'min_samples_leaf': 17}. Best is trial 3 with value: -1.0176866156267157.
[I 2026-06-02 21:55:44,067] Trial 12 finished with value: -2.577343200387279 and parameters: {'n_estimators': 592, 'max_depth': 17, 'min_samples_split': 32, 'min_samples_leaf': 25}. Best is trial 3 with value: -1.0176866156267157.
[I 2026-06-02 21:55:44,467] Trial 13 finished with value: -3.1471609934276 and parameters: {'n_estimators': 946, 'max_depth': 46, 'min_samples_split': 20, 'min_samples_leaf': 30}. Best is trial 3 with value: -1.0176866156267157.
[I 2026-06-02 21:55:44,563] Trial 14 finished with value: -1.7006350161760817 and parameters: {'n_estimators': 179, 'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 11}. Best is trial 3 with value: -1.0176866156267157.
[I 2026-06-02 21:55:44,785] Trial 15 finished with value: -1.8425294001889134 and parameters: {'n_estimators': 450, 'max_depth': 21, 'min_samples_split': 27, 'min_samples_leaf': 12}. Best is trial 3 with value: -1.0176866156267157.
[I 2026-06-02 21:55:44,943] Trial 16 finished with value: -2.693191592262025 and parameters: {'n_estimators': 353, 'max_depth': 32, 'min_samples_split': 6, 'min_samples_leaf': 26}. Best is trial 3 with value: -1.0176866156267157.
[I 2026-06-02 21:55:45,028] Trial 17 finished with value: -1.3889542689178322 and parameters: {'n_estimators': 167, 'max_depth': 50, 'min_samples_split': 25, 'min_samples_leaf': 7}. Best is trial 3 with value: -1.0176866156267157.
[I 2026-06-02 21:55:45,081] Trial 18 finished with value: -2.5346898325732203 and parameters: {'n_estimators': 104, 'max_depth': 43, 'min_samples_split': 23, 'min_samples_leaf': 24}. Best is trial 3 with value: -1.0176866156267157.
[I 2026-06-02 21:55:45,433] Trial 19 finished with value: -0.6660948652516652 and parameters: {'n_estimators': 794, 'max_depth': 13, 'min_samples_split': 13, 'min_samples_leaf': 4}. Best is trial 19 with value: -0.6660948652516652.
[I 2026-06-02 21:55:45,871] Trial 20 finished with value: -0.5296664030492806 and parameters: {'n_estimators': 877, 'max_depth': 35, 'min_samples_split': 12, 'min_samples_leaf': 3}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:46,057] Trial 21 finished with value: -2.3508100199373603 and parameters: {'n_estimators': 380, 'max_depth': 23, 'min_samples_split': 24, 'min_samples_leaf': 21}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:46,449] Trial 22 finished with value: -2.465671331775366 and parameters: {'n_estimators': 899, 'max_depth': 29, 'min_samples_split': 5, 'min_samples_leaf': 23}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:46,780] Trial 23 finished with value: -2.143425354751674 and parameters: {'n_estimators': 785, 'max_depth': 33, 'min_samples_split': 25, 'min_samples_leaf': 16}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:47,049] Trial 24 finished with value: -0.5709544932289036 and parameters: {'n_estimators': 570, 'max_depth': 27, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:47,124] Trial 25 finished with value: -2.2074416949301 and parameters: {'n_estimators': 128, 'max_depth': 36, 'min_samples_split': 11, 'min_samples_leaf': 17}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:47,526] Trial 26 finished with value: -2.5802212927169954 and parameters: {'n_estimators': 917, 'max_depth': 20, 'min_samples_split': 14, 'min_samples_leaf': 25}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:47,683] Trial 27 finished with value: -1.0301876597534563 and parameters: {'n_estimators': 306, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 6}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:48,077] Trial 28 finished with value: -2.925206453736279 and parameters: {'n_estimators': 937, 'max_depth': 43, 'min_samples_split': 21, 'min_samples_leaf': 28}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:48,428] Trial 29 finished with value: -2.2268212565758154 and parameters: {'n_estimators': 824, 'max_depth': 17, 'min_samples_split': 29, 'min_samples_leaf': 18}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:48,816] Trial 30 finished with value: -0.6225761184710048 and parameters: {'n_estimators': 827, 'max_depth': 46, 'min_samples_split': 11, 'min_samples_leaf': 4}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:48,965] Trial 31 finished with value: -2.9115099636693387 and parameters: {'n_estimators': 305, 'max_depth': 27, 'min_samples_split': 27, 'min_samples_leaf': 28}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:49,029] Trial 32 finished with value: -1.3625736558780772 and parameters: {'n_estimators': 106, 'max_depth': 30, 'min_samples_split': 14, 'min_samples_leaf': 8}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:49,137] Trial 33 finished with value: -1.810340346456048 and parameters: {'n_estimators': 207, 'max_depth': 23, 'min_samples_split': 31, 'min_samples_leaf': 11}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:49,381] Trial 34 finished with value: -3.3523231599578294 and parameters: {'n_estimators': 567, 'max_depth': 38, 'min_samples_split': 13, 'min_samples_leaf': 32}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:49,825] Trial 35 finished with value: -1.5657939007866286 and parameters: {'n_estimators': 967, 'max_depth': 20, 'min_samples_split': 17, 'min_samples_leaf': 10}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:50,015] Trial 36 finished with value: -2.188155543661646 and parameters: {'n_estimators': 356, 'max_depth': 11, 'min_samples_split': 20, 'min_samples_leaf': 17}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:50,121] Trial 37 finished with value: -1.530066336685871 and parameters: {'n_estimators': 146, 'max_depth': 21, 'min_samples_split': 30, 'min_samples_leaf': 8}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:50,278] Trial 38 finished with value: -1.6074554873086249 and parameters: {'n_estimators': 230, 'max_depth': 30, 'min_samples_split': 32, 'min_samples_leaf': 8}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:50,724] Trial 39 finished with value: -2.5158744185747643 and parameters: {'n_estimators': 705, 'max_depth': 41, 'min_samples_split': 9, 'min_samples_leaf': 24}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:50,987] Trial 40 finished with value: -2.241779832351988 and parameters: {'n_estimators': 431, 'max_depth': 35, 'min_samples_split': 21, 'min_samples_leaf': 18}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:51,114] Trial 41 finished with value: -1.0390632499468082 and parameters: {'n_estimators': 181, 'max_depth': 44, 'min_samples_split': 11, 'min_samples_leaf': 6}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:51,210] Trial 42 finished with value: -0.9629405900464441 and parameters: {'n_estimators': 136, 'max_depth': 34, 'min_samples_split': 23, 'min_samples_leaf': 1}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:51,569] Trial 43 finished with value: -1.1794301624776573 and parameters: {'n_estimators': 561, 'max_depth': 19, 'min_samples_split': 22, 'min_samples_leaf': 6}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:52,026] Trial 44 finished with value: -1.3937481048123614 and parameters: {'n_estimators': 722, 'max_depth': 25, 'min_samples_split': 31, 'min_samples_leaf': 5}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:52,276] Trial 45 finished with value: -3.038713020034084 and parameters: {'n_estimators': 407, 'max_depth': 14, 'min_samples_split': 30, 'min_samples_leaf': 29}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:52,474] Trial 46 finished with value: -2.236501628392813 and parameters: {'n_estimators': 332, 'max_depth': 37, 'min_samples_split': 27, 'min_samples_leaf': 18}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:52,819] Trial 47 finished with value: -3.0353554409724604 and parameters: {'n_estimators': 577, 'max_depth': 19, 'min_samples_split': 4, 'min_samples_leaf': 29}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:53,338] Trial 48 finished with value: -1.8010260228852792 and parameters: {'n_estimators': 911, 'max_depth': 35, 'min_samples_split': 12, 'min_samples_leaf': 12}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:53,735] Trial 49 finished with value: -2.595166012223089 and parameters: {'n_estimators': 754, 'max_depth': 46, 'min_samples_split': 29, 'min_samples_leaf': 25}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:54,078] Trial 50 finished with value: -3.006959668258182 and parameters: {'n_estimators': 678, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 29}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:54,409] Trial 51 finished with value: -2.4065531628209635 and parameters: {'n_estimators': 646, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 22}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:54,474] Trial 52 finished with value: -2.4554143280678415 and parameters: {'n_estimators': 104, 'max_depth': 16, 'min_samples_split': 19, 'min_samples_leaf': 23}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:54,828] Trial 53 finished with value: -1.4630064533113787 and parameters: {'n_estimators': 687, 'max_depth': 19, 'min_samples_split': 24, 'min_samples_leaf': 8}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:55,048] Trial 54 finished with value: -2.902748533378481 and parameters: {'n_estimators': 393, 'max_depth': 40, 'min_samples_split': 22, 'min_samples_leaf': 28}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:55,420] Trial 55 finished with value: -1.7902830321106087 and parameters: {'n_estimators': 692, 'max_depth': 33, 'min_samples_split': 4, 'min_samples_leaf': 12}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:55,597] Trial 56 finished with value: -1.9592935172015626 and parameters: {'n_estimators': 338, 'max_depth': 20, 'min_samples_split': 32, 'min_samples_leaf': 13}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:56,063] Trial 57 finished with value: -2.1914533849447535 and parameters: {'n_estimators': 903, 'max_depth': 35, 'min_samples_split': 26, 'min_samples_leaf': 17}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:56,434] Trial 58 finished with value: -2.5161477847790747 and parameters: {'n_estimators': 619, 'max_depth': 30, 'min_samples_split': 8, 'min_samples_leaf': 24}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:56,642] Trial 59 finished with value: -1.1923667012486938 and parameters: {'n_estimators': 352, 'max_depth': 10, 'min_samples_split': 22, 'min_samples_leaf': 6}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:57,179] Trial 60 finished with value: -1.8617441033853783 and parameters: {'n_estimators': 947, 'max_depth': 49, 'min_samples_split': 30, 'min_samples_leaf': 12}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:57,264] Trial 61 finished with value: -3.2697581468195898 and parameters: {'n_estimators': 113, 'max_depth': 48, 'min_samples_split': 15, 'min_samples_leaf': 31}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:57,824] Trial 62 finished with value: -1.9083223112943712 and parameters: {'n_estimators': 968, 'max_depth': 44, 'min_samples_split': 11, 'min_samples_leaf': 13}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:58,321] Trial 63 finished with value: -2.2317737131218505 and parameters: {'n_estimators': 866, 'max_depth': 22, 'min_samples_split': 7, 'min_samples_leaf': 18}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:58,933] Trial 64 finished with value: -0.8399742635091106 and parameters: {'n_estimators': 943, 'max_depth': 38, 'min_samples_split': 19, 'min_samples_leaf': 4}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:59,336] Trial 65 finished with value: -2.185510785101031 and parameters: {'n_estimators': 654, 'max_depth': 50, 'min_samples_split': 6, 'min_samples_leaf': 17}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:55:59,895] Trial 66 finished with value: -2.4469003369094176 and parameters: {'n_estimators': 890, 'max_depth': 40, 'min_samples_split': 23, 'min_samples_leaf': 23}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:56:00,199] Trial 67 finished with value: -2.666965226488302 and parameters: {'n_estimators': 423, 'max_depth': 22, 'min_samples_split': 27, 'min_samples_leaf': 26}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:56:00,840] Trial 68 finished with value: -2.193954253028522 and parameters: {'n_estimators': 881, 'max_depth': 47, 'min_samples_split': 17, 'min_samples_leaf': 17}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:56:01,382] Trial 69 finished with value: -2.6760193437573343 and parameters: {'n_estimators': 819, 'max_depth': 36, 'min_samples_split': 23, 'min_samples_leaf': 26}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:56:01,983] Trial 70 finished with value: -0.6547487329802154 and parameters: {'n_estimators': 901, 'max_depth': 23, 'min_samples_split': 13, 'min_samples_leaf': 4}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:56:02,404] Trial 71 finished with value: -2.228104629021839 and parameters: {'n_estimators': 621, 'max_depth': 11, 'min_samples_split': 16, 'min_samples_leaf': 18}. Best is trial 20 with value: -0.5296664030492806.
[I 2026-06-02 21:56:02,622] Trial 72 finished with value: -0.27183606800868343 and parameters: {'n_estimators': 358, 'max_depth': 34, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 72 with value: -0.27183606800868343.
[I 2026-06-02 21:56:03,037] Trial 73 finished with value: -2.1889300243143586 and parameters: {'n_estimators': 841, 'max_depth': 24, 'min_samples_split': 5, 'min_samples_leaf': 17}. Best is trial 72 with value: -0.27183606800868343.
[I 2026-06-02 21:56:03,419] Trial 74 finished with value: -0.8591296606597997 and parameters: {'n_estimators': 793, 'max_depth': 18, 'min_samples_split': 21, 'min_samples_leaf': 3}. Best is trial 72 with value: -0.27183606800868343.
[I 2026-06-02 21:56:03,492] Trial 75 finished with value: -2.3533919714955274 and parameters: {'n_estimators': 146, 'max_depth': 31, 'min_samples_split': 18, 'min_samples_leaf': 21}. Best is trial 72 with value: -0.27183606800868343.
[I 2026-06-02 21:56:03,833] Trial 76 finished with value: -1.6759983070237214 and parameters: {'n_estimators': 754, 'max_depth': 50, 'min_samples_split': 18, 'min_samples_leaf': 11}. Best is trial 72 with value: -0.27183606800868343.
[I 2026-06-02 21:56:04,224] Trial 77 finished with value: -0.6134275065916114 and parameters: {'n_estimators': 816, 'max_depth': 21, 'min_samples_split': 15, 'min_samples_leaf': 3}. Best is trial 72 with value: -0.27183606800868343.
[I 2026-06-02 21:56:04,297] Trial 78 finished with value: -2.4332333152474934 and parameters: {'n_estimators': 122, 'max_depth': 49, 'min_samples_split': 27, 'min_samples_leaf': 23}. Best is trial 72 with value: -0.27183606800868343.
[I 2026-06-02 21:56:04,545] Trial 79 finished with value: -1.469049387809039 and parameters: {'n_estimators': 468, 'max_depth': 17, 'min_samples_split': 6, 'min_samples_leaf': 9}. Best is trial 72 with value: -0.27183606800868343.
[I 2026-06-02 21:56:04,870] Trial 80 finished with value: -1.5137941754484534 and parameters: {'n_estimators': 594, 'max_depth': 39, 'min_samples_split': 22, 'min_samples_leaf': 9}. Best is trial 72 with value: -0.27183606800868343.
[I 2026-06-02 21:56:05,385] Trial 81 finished with value: -2.3161198091330446 and parameters: {'n_estimators': 960, 'max_depth': 40, 'min_samples_split': 19, 'min_samples_leaf': 20}. Best is trial 72 with value: -0.27183606800868343.
[I 2026-06-02 21:56:05,656] Trial 82 finished with value: -2.59456974904458 and parameters: {'n_estimators': 478, 'max_depth': 20, 'min_samples_split': 13, 'min_samples_leaf': 25}. Best is trial 72 with value: -0.27183606800868343.
[I 2026-06-02 21:56:05,742] Trial 83 finished with value: -0.26352476362981275 and parameters: {'n_estimators': 112, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 83 with value: -0.26352476362981275.
[I 2026-06-02 21:56:06,318] Trial 84 finished with value: -0.7421531662038978 and parameters: {'n_estimators': 870, 'max_depth': 38, 'min_samples_split': 16, 'min_samples_leaf': 4}. Best is trial 83 with value: -0.26352476362981275.
[I 2026-06-02 21:56:06,769] Trial 85 finished with value: -2.00513380195364 and parameters: {'n_estimators': 542, 'max_depth': 29, 'min_samples_split': 7, 'min_samples_leaf': 14}. Best is trial 83 with value: -0.26352476362981275.

In [50]:
study.best_params

{'n_estimators': 940,
 'max_depth': 45,
 'min_samples_split': 3,
 'min_samples_leaf': 1}

In [51]:
best_params = study.best_params

In [52]:
import matplotlib.pyplot as plt

In [53]:
optuna.visualization.plot_optimization_history(study)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'mode': 'markers',
              'name': 'Objective Value',
              'type': 'scatter',
              'x': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
                    18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
                    34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
                    50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
                    66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
                    82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
                    98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                    111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122,
                    123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134,
                    135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146,
                    147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158,
                    159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
                    171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
                    183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
                    195, 196, 197, 198, 199],
              'y': [-2.3128756957884375, -2.8993306860968433, -3.3568205475025734,
                    -1.0176866156267157, -1.5669691458421142, -1.7883669216794122,
                    -2.2053409915133995, -1.1254780626668444, -2.6824297859660917,
                    -2.071032034206092, -3.1807387437168035, -2.1921665587526635,
                    -2.577343200387279, -3.1471609934276, -1.7006350161760817,
                    -1.8425294001889134, -2.693191592262025, -1.3889542689178322,
                    -2.5346898325732203, -0.6660948652516652, -0.5296664030492806,
                    -2.3508100199373603, -2.465671331775366, -2.143425354751674,
                    -0.5709544932289036, -2.2074416949301, -2.5802212927169954,
                    -1.0301876597534563, -2.925206453736279, -2.2268212565758154,
                    -0.6225761184710048, -2.9115099636693387, -1.3625736558780772,
                    -1.810340346456048, -3.3523231599578294, -1.5657939007866286,
                    -2.188155543661646, -1.530066336685871, -1.6074554873086249,
                    -2.5158744185747643, -2.241779832351988, -1.0390632499468082,
                    -0.9629405900464441, -1.1794301624776573, -1.3937481048123614,
                    -3.038713020034084, -2.236501628392813, -3.0353554409724604,
                    -1.8010260228852792, -2.595166012223089, -3.006959668258182,
                    -2.4065531628209635, -2.4554143280678415, -1.4630064533113787,
                    -2.902748533378481, -1.7902830321106087, -1.9592935172015626,
                    -2.1914533849447535, -2.5161477847790747, -1.1923667012486938,
                    -1.8617441033853783, -3.2697581468195898, -1.9083223112943712,
                    -2.2317737131218505, -0.8399742635091106, -2.185510785101031,
                    -2.4469003369094176, -2.666965226488302, -2.193954253028522,
                    -2.6760193437573343, -0.6547487329802154, -2.228104629021839,
                    -0.27183606800868343, -2.1889300243143586, -0.8591296606597997,
                    -2.3533919714955274, -1.6759983070237214, -0.6134275065916114,
                    -2.4332333152474934, -1.469049387809039, -1.5137941754484534,
                    -2.3161198091330446, -2.59456974904458, -0.26352476362981275,
                    -0.7421531662038978, -2.00513380195364, -0.8427268317379859,
                    -2.9231762087728677, -2.350387522284133, -2.2509942898288045,
                    -2.223581179189172, -3.028823093266374, -0.24485454519965763,
                    -1.6930969077927465, -1.6750422562880931, -3.0247015593614703,
                    -1.015066012294838, -2.0477093090891514, -3.150280877727666,
                    -2.587547912579123, -2.820623780010463, -0.5298470007596979,
                    -3.2425438952089545, -2.0795106199841884, -2.5907253425018615,
                    -2.160678587039768, -3.0065741170755933, -2.5835594603788055,
                    -2.4603992258713676, -0.9829478865864157, -1.8207414419377492,
                    -2.5852111250818703, -2.2293676616346363, -2.1479511782043272,
                    -0.5668757653396618, -2.2474862457025067, -2.9224135794266117,
                    -3.365933482315209, -3.3249070703943375, -2.1836080580542854,
                    -2.353379488934982, -1.462711405710093, -2.3107443228844664,
                    -1.800290082328474, -3.335376493225108, -2.8036771045532918,
                    -2.779894967188965, -2.0024974865249474, -0.2038525021397634,
                    -1.465001486804055, -2.7758022639190494, -1.4585832507255319,
                    -3.295774380908251, -3.2408927363321616, -0.8578802358306936,
                    -2.3954422100387385, -2.39325823880122, -2.905578201054804,
                    -1.9342137350264916, -2.317884862980963, -0.27727779640208544,
                    -1.9992616855988132, -2.6795987764171145, -3.2357251966278513,
                    -1.4637878115619352, -1.6670984608550707, -0.7992279675611433,
                    -2.3596563065702854, -2.1384243116130013, -0.33511848159123053,
                    -0.41615902587262577, -1.795628394152919, -2.6947559437949,
                    -3.1421130503657393, -2.5582494912720914, -2.1369807652177344,
                    -2.519898800683006, -3.0308211050433225, -2.0893269672050123,
                    -1.920904104945702, -1.6822873776177132, -2.4305231436367665,
                    -2.231958740771789, -0.8678812923018986, -2.26565038095684,
                    -1.3746844062589028, -1.005357183894338, -3.0157597102354456,
                    -3.3562455056565526, -2.9221784787364187, -2.399710886972611,
                    -1.475633466587687, -2.000946871738448, -2.310963217044788,
                    -2.1271386767405533, -0.8170217416728509, -2.7096866196333926,
                    -2.305861359679968, -3.129365296348909, -2.5048735185050943,
                    -2.5120490846383245, -2.6794768245183382, -2.8335739517133156,
                    -3.04091873529656, -1.9092800808448582, -2.200390738615807,
                    -2.2355793278944853, -3.2208640309677152, -2.692415995640765,
                    -2.695964030654509, -2.523150350743638, -3.0240293434017445,
                    -2.926735479029458, -1.1896484077345144, -2.3473701165668723,
                    -1.807060894179753, -1.906728095483453, -2.2734711093640767,
                    -2.906080789804657, -3.1262641923373566]},
             {'mode': 'lines',
              'name': 'Best Value',
              'type': 'scatter',
              'x': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
                    18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
                    34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
                    50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
                    66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
                    82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
                    98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                    111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122,
                    123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134,
                    135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146,
                    147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158,
                    159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
                    171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
                    183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
                    195, 196, 197, 198, 199],
              'y': [-2.3128756957884375, -2.3128756957884375, -2.3128756957884375,
                    -1.0176866156267157, -1.0176866156267157, -1.0176866156267157,
                    -1.0176866156267157, -1.0176866156267157, -1.0176866156267157,
                    -1.0176866156267157, -1.0176866156267157, -1.0176866156267157,
                    -1.0176866156267157, -1.0176866156267157, -1.0176866156267157,
                    -1.0176866156267157, -1.0176866156267157, -1.0176866156267157,
                    -1.0176866156267157, -0.6660948652516652, -0.5296664030492806,
                    -0.5296664030492806, -0.5296664030492806, -0.5296664030492806,
                    -0.5296664030492806, -0.5296664030492806, -0.5296664030492806,
                    -0.5296664030492806, -0.5296664030492806, -0.5296664030492806,
                    -0.5296664030492806, -0.5296664030492806, -0.5296664030492806,
                    -0.5296664030492806, -0.5296664030492806, -0.5296664030492806,
                    -0.5296664030492806, -0.5296664030492806, -0.5296664030492806,
                    -0.5296664030492806, -0.5296664030492806, -0.5296664030492806,
                    -0.5296664030492806, -0.5296664030492806, -0.5296664030492806,
                    -0.5296664030492806, -0.5296664030492806, -0.5296664030492806,
                    -0.5296664030492806, -0.5296664030492806, -0.5296664030492806,
                    -0.5296664030492806, -0.5296664030492806, -0.5296664030492806,
                    -0.5296664030492806, -0.5296664030492806, -0.5296664030492806,
                    -0.5296664030492806, -0.5296664030492806, -0.5296664030492806,
                    -0.5296664030492806, -0.5296664030492806, -0.5296664030492806,
                    -0.5296664030492806, -0.5296664030492806, -0.5296664030492806,
                    -0.5296664030492806, -0.5296664030492806, -0.5296664030492806,
                    -0.5296664030492806, -0.5296664030492806, -0.5296664030492806,
                    -0.27183606800868343, -0.27183606800868343,
                    -0.27183606800868343, -0.27183606800868343,
                    -0.27183606800868343, -0.27183606800868343,
                    -0.27183606800868343, -0.27183606800868343,
                    -0.27183606800868343, -0.27183606800868343,
                    -0.27183606800868343, -0.26352476362981275,
                    -0.26352476362981275, -0.26352476362981275,
                    -0.26352476362981275, -0.26352476362981275,
                    -0.26352476362981275, -0.26352476362981275,
                    -0.26352476362981275, -0.26352476362981275,
                    -0.24485454519965763, -0.24485454519965763,
                    -0.24485454519965763, -0.24485454519965763,
                    -0.24485454519965763, -0.24485454519965763,
                    -0.24485454519965763, -0.24485454519965763,
                    -0.24485454519965763, -0.24485454519965763,
                    -0.24485454519965763, -0.24485454519965763,
                    -0.24485454519965763, -0.24485454519965763,
                    -0.24485454519965763, -0.24485454519965763,
                    -0.24485454519965763, -0.24485454519965763,
                    -0.24485454519965763, -0.24485454519965763,
                    -0.24485454519965763, -0.24485454519965763,
                    -0.24485454519965763, -0.24485454519965763,
                    -0.24485454519965763, -0.24485454519965763,
                    -0.24485454519965763, -0.24485454519965763,
                    -0.24485454519965763, -0.24485454519965763,
                    -0.24485454519965763, -0.24485454519965763,
                    -0.24485454519965763, -0.24485454519965763,
                    -0.24485454519965763, -0.24485454519965763,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634,
                    -0.2038525021397634, -0.2038525021397634, -0.2038525021397634]},
             {'marker': {'color': '#cccccc'},
              'mode': 'markers',
              'name': 'Infeasible Trial',
              'showlegend': False,
              'type': 'scatter',
              'x': [],
              'y': []}],
    'layout': {'template': '...',
               'title': {'text': 'Optimization History Plot'},
               'xaxis': {'title': {'text': 'Trial'}},
               'yaxis': {'title': {'text': 'Objective Value'}}}
})

In [54]:
optuna.visualization.plot_parallel_coordinate(study)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'dimensions': [{'label': 'Objective Value',
                              'range': [-3.365933482315209, -0.2038525021397634],
                              'values': [-2.3128756957884375, -2.8993306860968433,
                                         -3.3568205475025734, -1.0176866156267157,
                                         -1.5669691458421142, -1.7883669216794122,
                                         -2.2053409915133995, -1.1254780626668444,
                                         -2.6824297859660917, -2.071032034206092,
                                         -3.1807387437168035, -2.1921665587526635,
                                         -2.577343200387279, -3.1471609934276,
                                         -1.7006350161760817, -1.8425294001889134,
                                         -2.693191592262025, -1.3889542689178322,
                                         -2.5346898325732203, -0.6660948652516652,
                                         -0.5296664030492806, -2.3508100199373603,
                                         -2.465671331775366, -2.143425354751674,
                                         -0.5709544932289036, -2.2074416949301,
                                         -2.5802212927169954, -1.0301876597534563,
                                         -2.925206453736279, -2.2268212565758154,
                                         -0.6225761184710048, -2.9115099636693387,
                                         -1.3625736558780772, -1.810340346456048,
                                         -3.3523231599578294, -1.5657939007866286,
                                         -2.188155543661646, -1.530066336685871,
                                         -1.6074554873086249, -2.5158744185747643,
                                         -2.241779832351988, -1.0390632499468082,
                                         -0.9629405900464441, -1.1794301624776573,
                                         -1.3937481048123614, -3.038713020034084,
                                         -2.236501628392813, -3.0353554409724604,
                                         -1.8010260228852792, -2.595166012223089,
                                         -3.006959668258182, -2.4065531628209635,
                                         -2.4554143280678415, -1.4630064533113787,
                                         -2.902748533378481, -1.7902830321106087,
                                         -1.9592935172015626, -2.1914533849447535,
                                         -2.5161477847790747, -1.1923667012486938,
                                         -1.8617441033853783, -3.2697581468195898,
                                         -1.9083223112943712, -2.2317737131218505,
                                         -0.8399742635091106, -2.185510785101031,
                                         -2.4469003369094176, -2.666965226488302,
                                         -2.193954253028522, -2.6760193437573343,
                                         -0.6547487329802154, -2.228104629021839,
                                         -0.27183606800868343, -2.1889300243143586,
                                         -0.8591296606597997, -2.3533919714955274,
                                         -1.6759983070237214, -0.6134275065916114,
                                         -2.4332333152474934, -1.469049387809039,
                                         -1.5137941754484534, -2.3161198091330446,
                                         -2.59456974904458, -0.26352476362981275,
                                         -0.7421531662038978, -2.00513380195364,
                                         -0.8427268317379859, -2.9231762087728677,
                                         -2.350387522284133, -2.2509942898288045,
                                         -2.223581179189172, -3.028823093266374,
                                         -0.24485454519965763, -1.6930969077927465,
                                         -1.6750422562880931, -3.0247015593614703,
                                         -1.015066012294838, -2.0477093090891514,
                                         -3.150280877727666, -2.587547912579123,
                                         -2.820623780010463, -0.5298470007596979,
                                         -3.2425438952089545, -2.0795106199841884,
                                         -2.5907253425018615, -2.160678587039768,
                                         -3.0065741170755933, -2.5835594603788055,
                                         -2.4603992258713676, -0.9829478865864157,
                                         -1.8207414419377492, -2.5852111250818703,
                                         -2.2293676616346363, -2.1479511782043272,
                                         -0.5668757653396618, -2.2474862457025067,
                                         -2.9224135794266117, -3.365933482315209,
                                         -3.3249070703943375, -2.1836080580542854,
                                         -2.353379488934982, -1.462711405710093,
                                         -2.3107443228844664, -1.800290082328474,
                                         -3.335376493225108, -2.8036771045532918,
                                         -2.779894967188965, -2.0024974865249474,
                                         -0.2038525021397634, -1.465001486804055,
                                         -2.7758022639190494, -1.4585832507255319,
                                         -3.295774380908251, -3.2408927363321616,
                                         -0.8578802358306936, -2.3954422100387385,
                                         -2.39325823880122, -2.905578201054804,
                                         -1.9342137350264916, -2.317884862980963,
                                         -0.27727779640208544, -1.9992616855988132,
                                         -2.6795987764171145, -3.2357251966278513,
                                         -1.4637878115619352, -1.6670984608550707,
                                         -0.7992279675611433, -2.3596563065702854,
                                         -2.1384243116130013, -0.33511848159123053,
                                         -0.41615902587262577, -1.795628394152919,
                                         -2.6947559437949, -3.1421130503657393,
                                         -2.5582494912720914, -2.1369807652177344,
                                         -2.519898800683006, -3.0308211050433225,
                                         -2.0893269672050123, -1.920904104945702,
                                         -1.6822873776177132, -2.4305231436367665,
                                         -2.231958740771789, -0.8678812923018986,
                                         -2.26565038095684, -1.3746844062589028,
                                         -1.005357183894338, -3.0157597102354456,
                                         -3.3562455056565526, -2.9221784787364187,
                                         -2.399710886972611, -1.475633466587687,
                                         -2.000946871738448, -2.310963217044788,
                                         -2.1271386767405533, -0.8170217416728509,
                                         -2.7096866196333926, -2.305861359679968,
                                         -3.129365296348909, -2.5048735185050943,
                                         -2.5120490846383245, -2.6794768245183382,
                                         -2.8335739517133156, -3.04091873529656,
                                         -1.9092800808448582, -2.200390738615807,
                                         -2.2355793278944853, -3.2208640309677152,
                                         -2.692415995640765, -2.695964030654509,
                                         -2.523150350743638, -3.0240293434017445,
                                         -2.926735479029458, -1.1896484077345144,
                                         -2.3473701165668723, -1.807060894179753,
                                         -1.906728095483453, -2.2734711093640767,
                                         -2.906080789804657, -3.1262641923373566]},
                             {'label': 'max_depth',
                              'range': [10, 50],
                              'values': [48, 16, 39, 18, 31, 15, 42, 11, 48, 14,
                                         30, 37, 17, 46, 18, 21, 32, 50, 43, 13,
                                         35, 23, 29, 33, 27, 36, 20, 13, 43, 17,
                                         46, 27, 30, 23, 38, 20, 11, 21, 30, 41,
                                         35, 44, 34, 19, 25, 14, 37, 19, 35, 46,
                                         13, 10, 16, 19, 40, 33, 20, 35, 30, 10,
                                         49, 48, 44, 22, 38, 50, 40, 22, 47, 36,
                                         23, 11, 34, 24, 18, 31, 50, 21, 49, 17,
                                         39, 40, 20, 14, 38, 29, 35, 35, 16, 34,
                                         36, 25, 12, 38, 10, 38, 42, 43, 41, 27,
                                         47, 46, 13, 33, 23, 42, 32, 14, 14, 43,
                                         50, 48, 13, 47, 29, 36, 25, 49, 46, 32,
                                         38, 46, 46, 17, 13, 31, 16, 39, 45, 43,
                                         25, 29, 45, 32, 20, 34, 24, 41, 32, 11,
                                         18, 34, 24, 35, 47, 50, 19, 16, 24, 17,
                                         21, 28, 38, 13, 21, 18, 25, 20, 31, 19,
                                         23, 46, 30, 40, 24, 50, 16, 21, 31, 26,
                                         20, 32, 17, 19, 33, 12, 50, 37, 26, 49,
                                         17, 44, 16, 31, 43, 22, 46, 35, 23, 31,
                                         22, 33, 43, 26, 39, 32, 47, 48, 35, 33]},
                             {'label': 'min_samples_leaf',
                              'range': [1, 32],
                              'values': [20, 28, 32, 6, 10, 12, 17, 6, 26, 15, 30,
                                         17, 25, 30, 11, 12, 26, 7, 24, 4, 3, 21,
                                         23, 16, 4, 17, 25, 6, 28, 18, 4, 28, 8,
                                         11, 32, 10, 17, 8, 8, 24, 18, 6, 1, 6, 5,
                                         29, 18, 29, 12, 25, 29, 22, 23, 8, 28, 12,
                                         13, 17, 24, 6, 12, 31, 13, 18, 4, 17, 23,
                                         26, 17, 26, 4, 18, 2, 17, 3, 21, 11, 3,
                                         23, 9, 9, 20, 25, 2, 4, 14, 2, 28, 21, 19,
                                         18, 29, 1, 11, 10, 29, 6, 14, 30, 25, 27,
                                         1, 31, 15, 25, 16, 29, 25, 23, 3, 12, 25,
                                         18, 16, 4, 19, 28, 32, 32, 17, 21, 9, 20,
                                         12, 32, 27, 27, 14, 1, 5, 27, 9, 32, 31,
                                         5, 22, 22, 28, 13, 20, 1, 14, 26, 31, 9,
                                         11, 5, 21, 16, 2, 3, 12, 26, 30, 24, 16,
                                         24, 29, 15, 13, 11, 22, 18, 5, 19, 8, 6,
                                         29, 32, 28, 22, 9, 14, 20, 16, 5, 26, 20,
                                         30, 24, 24, 26, 27, 29, 13, 17, 18, 31,
                                         26, 26, 24, 29, 28, 5, 21, 12, 13, 19, 28,
                                         30]},
                             {'label': 'min_samples_split',
                              'range': [2, 32],
                              'values': [24, 3, 2, 7, 15, 11, 8, 20, 31, 23, 3,
                                         11, 32, 20, 3, 27, 6, 25, 23, 13, 12, 24,
                                         5, 25, 2, 11, 14, 10, 21, 29, 11, 27, 14,
                                         31, 13, 17, 20, 30, 32, 9, 21, 11, 23, 22,
                                         31, 30, 27, 4, 12, 29, 7, 5, 19, 24, 22,
                                         4, 32, 26, 8, 22, 30, 15, 11, 7, 19, 6,
                                         23, 27, 17, 23, 13, 16, 2, 5, 21, 18, 18,
                                         15, 27, 6, 22, 19, 13, 3, 16, 7, 21, 17,
                                         4, 31, 16, 31, 5, 4, 27, 21, 10, 32, 12,
                                         25, 17, 14, 11, 21, 22, 4, 15, 6, 4, 23,
                                         13, 32, 26, 5, 3, 25, 10, 2, 18, 32, 16,
                                         3, 16, 16, 32, 11, 30, 21, 3, 32, 32, 14,
                                         27, 25, 15, 9, 5, 18, 29, 25, 6, 14, 17,
                                         28, 17, 17, 4, 6, 29, 7, 7, 8, 3, 29, 26,
                                         13, 16, 24, 5, 10, 8, 20, 4, 15, 22, 20,
                                         9, 7, 14, 32, 7, 19, 12, 5, 6, 12, 11, 25,
                                         12, 5, 4, 6, 7, 13, 15, 25, 13, 5, 6, 29,
                                         9, 25, 5, 26, 24, 9, 20, 6, 2, 23]},
                             {'label': 'n_estimators',
                              'range': [104, 997],
                              'values': [437, 240, 641, 850, 374, 651, 510, 633,
                                         158, 374, 209, 333, 592, 946, 179, 450,
                                         353, 167, 104, 794, 877, 380, 899, 785,
                                         570, 128, 917, 306, 937, 824, 827, 305,
                                         106, 207, 567, 967, 356, 146, 230, 705,
                                         431, 181, 136, 561, 722, 407, 332, 577,
                                         911, 754, 678, 646, 104, 687, 393, 692,
                                         338, 903, 619, 352, 947, 113, 968, 866,
                                         943, 654, 890, 423, 881, 819, 901, 621,
                                         358, 841, 793, 146, 754, 816, 122, 468,
                                         594, 960, 478, 112, 870, 542, 459, 437,
                                         693, 123, 449, 948, 276, 185, 861, 206,
                                         762, 776, 435, 873, 192, 388, 915, 956,
                                         364, 813, 151, 416, 657, 165, 176, 832,
                                         439, 482, 110, 205, 966, 301, 138, 166,
                                         667, 626, 956, 349, 625, 729, 716, 955,
                                         940, 439, 635, 855, 150, 997, 865, 959,
                                         656, 568, 597, 220, 734, 415, 914, 457,
                                         232, 513, 670, 215, 263, 701, 252, 208,
                                         553, 665, 155, 266, 657, 133, 561, 579,
                                         118, 207, 811, 628, 355, 420, 191, 268,
                                         172, 200, 836, 937, 793, 557, 360, 579,
                                         157, 329, 524, 848, 945, 617, 281, 699,
                                         453, 516, 309, 916, 665, 658, 236, 130,
                                         408, 214, 306, 725, 263, 516, 555, 939]}],
              'labelangle': 30,
              'labelside': 'bottom',
              'line': {'color': [-2.3128756957884375, -2.8993306860968433,
                                 -3.3568205475025734, -1.0176866156267157,
                                 -1.5669691458421142, -1.7883669216794122,
                                 -2.2053409915133995, -1.1254780626668444,
                                 -2.6824297859660917, -2.071032034206092,
                                 -3.1807387437168035, -2.1921665587526635,
                                 -2.577343200387279, -3.1471609934276,
                                 -1.7006350161760817, -1.8425294001889134,
                                 -2.693191592262025, -1.3889542689178322,
                                 -2.5346898325732203, -0.6660948652516652,
                                 -0.5296664030492806, -2.3508100199373603,
                                 -2.465671331775366, -2.143425354751674,
                                 -0.5709544932289036, -2.2074416949301,
                                 -2.5802212927169954, -1.0301876597534563,
                                 -2.925206453736279, -2.2268212565758154,
                                 -0.6225761184710048, -2.9115099636693387,
                                 -1.3625736558780772, -1.810340346456048,
                                 -3.3523231599578294, -1.5657939007866286,
                                 -2.188155543661646, -1.530066336685871,
                                 -1.6074554873086249, -2.5158744185747643,
                                 -2.241779832351988, -1.0390632499468082,
                                 -0.9629405900464441, -1.1794301624776573,
                                 -1.3937481048123614, -3.038713020034084,
                                 -2.236501628392813, -3.0353554409724604,
                                 -1.8010260228852792, -2.595166012223089,
                                 -3.006959668258182, -2.4065531628209635,
                                 -2.4554143280678415, -1.4630064533113787,
                                 -2.902748533378481, -1.7902830321106087,
                                 -1.9592935172015626, -2.1914533849447535,
                                 -2.5161477847790747, -1.1923667012486938,
                                 -1.8617441033853783, -3.2697581468195898,
                                 -1.9083223112943712, -2.2317737131218505,
                                 -0.8399742635091106, -2.185510785101031,
                                 -2.4469003369094176, -2.666965226488302,
                                 -2.193954253028522, -2.6760193437573343,
                                 -0.6547487329802154, -2.228104629021839,
                                 -0.27183606800868343, -2.1889300243143586,
                                 -0.8591296606597997, -2.3533919714955274,
                                 -1.6759983070237214, -0.6134275065916114,
                                 -2.4332333152474934, -1.469049387809039,
                                 -1.5137941754484534, -2.3161198091330446,
                                 -2.59456974904458, -0.26352476362981275,
                                 -0.7421531662038978, -2.00513380195364,
                                 -0.8427268317379859, -2.9231762087728677,
                                 -2.350387522284133, -2.2509942898288045,
                                 -2.223581179189172, -3.028823093266374,
                                 -0.24485454519965763, -1.6930969077927465,
                                 -1.6750422562880931, -3.0247015593614703,
                                 -1.015066012294838, -2.0477093090891514,
                                 -3.150280877727666, -2.587547912579123,
                                 -2.820623780010463, -0.5298470007596979,
                                 -3.2425438952089545, -2.0795106199841884,
                                 -2.5907253425018615, -2.160678587039768,
                                 -3.0065741170755933, -2.5835594603788055,
                                 -2.4603992258713676, -0.9829478865864157,
                                 -1.8207414419377492, -2.5852111250818703,
                                 -2.2293676616346363, -2.1479511782043272,
                                 -0.5668757653396618, -2.2474862457025067,
                                 -2.9224135794266117, -3.365933482315209,
                                 -3.3249070703943375, -2.1836080580542854,

In [55]:
optuna.visualization.plot_slice(study, params=['n_estimators', 'max_depth', 'min_samples_leaf', 'min_samples_split'])

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'marker': {'color': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
                                   14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
                                   26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
                                   38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
                                   50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
                                   62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
                                   74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
                                   86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
                                   98, 99, 100, 101, 102, 103, 104, 105, 106, 107,
                                   108, 109, 110, 111, 112, 113, 114, 115, 116,
                                   117, 118, 119, 120, 121, 122, 123, 124, 125,
                                   126, 127, 128, 129, 130, 131, 132, 133, 134,
                                   135, 136, 137, 138, 139, 140, 141, 142, 143,
                                   144, 145, 146, 147, 148, 149, 150, 151, 152,
                                   153, 154, 155, 156, 157, 158, 159, 160, 161,
                                   162, 163, 164, 165, 166, 167, 168, 169, 170,
                                   171, 172, 173, 174, 175, 176, 177, 178, 179,
                                   180, 181, 182, 183, 184, 185, 186, 187, 188,
                                   189, 190, 191, 192, 193, 194, 195, 196, 197,
                                   198, 199],
                         'colorbar': {'title': {'text': 'Trial'}, 'x': 1.0, 'xpad': 40},
                         'colorscale': [[0.0, 'rgb(247,251,255)'], [0.125,
                                        'rgb(222,235,247)'], [0.25,
                                        'rgb(198,219,239)'], [0.375,
                                        'rgb(158,202,225)'], [0.5,
                                        'rgb(107,174,214)'], [0.625,
                                        'rgb(66,146,198)'], [0.75,
                                        'rgb(33,113,181)'], [0.875,
                                        'rgb(8,81,156)'], [1.0, 'rgb(8,48,107)']],
                         'line': {'color': 'Grey', 'width': 0.5},
                         'showscale': True},
              'mode': 'markers',
              'name': 'Feasible Trial',
              'showlegend': False,
              'type': 'scatter',
              'x': [48, 16, 39, 18, 31, 15, 42, 11, 48, 14, 30, 37, 17, 46, 18,
                    21, 32, 50, 43, 13, 35, 23, 29, 33, 27, 36, 20, 13, 43, 17, 46,
                    27, 30, 23, 38, 20, 11, 21, 30, 41, 35, 44, 34, 19, 25, 14, 37,
                    19, 35, 46, 13, 10, 16, 19, 40, 33, 20, 35, 30, 10, 49, 48, 44,
                    22, 38, 50, 40, 22, 47, 36, 23, 11, 34, 24, 18, 31, 50, 21, 49,
                    17, 39, 40, 20, 14, 38, 29, 35, 35, 16, 34, 36, 25, 12, 38, 10,
                    38, 42, 43, 41, 27, 47, 46, 13, 33, 23, 42, 32, 14, 14, 43, 50,
                    48, 13, 47, 29, 36, 25, 49, 46, 32, 38, 46, 46, 17, 13, 31, 16,
                    39, 45, 43, 25, 29, 45, 32, 20, 34, 24, 41, 32, 11, 18, 34, 24,
                    35, 47, 50, 19, 16, 24, 17, 21, 28, 38, 13, 21, 18, 25, 20, 31,
                    19, 23, 46, 30, 40, 24, 50, 16, 21, 31, 26, 20, 32, 17, 19, 33,
                    12, 50, 37, 26, 49, 17, 44, 16, 31, 43, 22, 46, 35, 23, 31, 22,
                    33, 43, 26, 39, 32, 47, 48, 35, 33],
              'xaxis': 'x',
              'y': [-2.3128756957884375, -2.8993306860968433, -3.3568205475025734,
                    -1.0176866156267157, -1.5669691458421142, -1.7883669216794122,
                    -2.2053409915133995, -1.1254780626668444, -2.6824297859660917,
                    -2.071032034206092, -3.1807387437168035, -2.1921665587526635,
                    -2.577343200387279, -3.1471609934276, -1.7006350161760817,
                    -1.8425294001889134, -2.693191592262025, -1.3889542689178322,
                    -2.5346898325732203, -0.6660948652516652, -0.5296664030492806,
                    -2.3508100199373603, -2.465671331775366, -2.143425354751674,
                    -0.5709544932289036, -2.2074416949301, -2.5802212927169954,
                    -1.0301876597534563, -2.925206453736279, -2.2268212565758154,
                    -0.6225761184710048, -2.9115099636693387, -1.3625736558780772,
                    -1.810340346456048, -3.3523231599578294, -1.5657939007866286,
                    -2.188155543661646, -1.530066336685871, -1.6074554873086249,
                    -2.5158744185747643, -2.241779832351988, -1.0390632499468082,
                    -0.9629405900464441, -1.1794301624776573, -1.3937481048123614,
                    -3.038713020034084, -2.236501628392813, -3.0353554409724604,
                    -1.8010260228852792, -2.595166012223089, -3.006959668258182,
                    -2.4065531628209635, -2.4554143280678415, -1.4630064533113787,
                    -2.902748533378481, -1.7902830321106087, -1.9592935172015626,
                    -2.1914533849447535, -2.5161477847790747, -1.1923667012486938,
                    -1.8617441033853783, -3.2697581468195898, -1.9083223112943712,
                    -2.2317737131218505, -0.8399742635091106, -2.185510785101031,
                    -2.4469003369094176, -2.666965226488302, -2.193954253028522,
                    -2.6760193437573343, -0.6547487329802154, -2.228104629021839,
                    -0.27183606800868343, -2.1889300243143586, -0.8591296606597997,
                    -2.3533919714955274, -1.6759983070237214, -0.6134275065916114,
                    -2.4332333152474934, -1.469049387809039, -1.5137941754484534,
                    -2.3161198091330446, -2.59456974904458, -0.26352476362981275,
                    -0.7421531662038978, -2.00513380195364, -0.8427268317379859,
                    -2.9231762087728677, -2.350387522284133, -2.2509942898288045,
                    -2.223581179189172, -3.028823093266374, -0.24485454519965763,
                    -1.6930969077927465, -1.6750422562880931, -3.0247015593614703,
                    -1.015066012294838, -2.0477093090891514, -3.150280877727666,
                    -2.587547912579123, -2.820623780010463, -0.5298470007596979,
                    -3.2425438952089545, -2.0795106199841884, -2.5907253425018615,
                    -2.160678587039768, -3.0065741170755933, -2.5835594603788055,
                    -2.4603992258713676, -0.9829478865864157, -1.8207414419377492,
                    -2.5852111250818703, -2.2293676616346363, -2.1479511782043272,
                    -0.5668757653396618, -2.2474862457025067, -2.9224135794266117,
                    -3.365933482315209, -3.3249070703943375, -2.1836080580542854,
                    -2.353379488934982, -1.462711405710093, -2.3107443228844664,
                    -1.800290082328474, -3.335376493225108, -2.8036771045532918,
                    -2.779894967188965, -2.0024974865249474, -0.2038525021397634,
                    -1.465001486804055, -2.7758022639190494, -1.4585832507255319,
                    -3.295774380908251, -3.2408927363321616, -0.8578802358306936,
                    -2.3954422100387385, -2.39325823880122, -2.905578201054804,
                    -1.9342137350264916, -2.317884862980963, -0.27727779640208544,
                    -1.9992616855988132, -2.6795987764171145, -3.2357251966278513,
                    -1.4637878115619352, -1.6670984608550707, -0.7992279675611433,
                    -2.3596563065702854, -2.1384243116130013, -0.33511848159123053,
                    -0.41615902587262577, -1.795628394152919, -2.6947559437949,
                    -3.1421130503657393, -2.5582494912720914, -2.1369807652177344,
                    -2.519898800683006, -3.0308211050433225, -2.0893269672050123,
                    -1.920904104945702, -1.6822873776177132, -2.4305231436367665,
                    -2.231958740771789, -0.8678812923018986, -2.26565038095684,
                    -1.3746844062589028, -1.005357183894338, -3.0157597102354456,
                    -3.3562455056565526, -2.9221784787364187, -2.399710886972611,
                    -1.475633466587687, -2.000946871738448, -2.310963217044788,
                    -2.1271386767405533, -0.8170217416728509, -2.7096866196333926,
                    -2.305861359679968, -3.129365296348909, -2.5048735185050943,
                    -2.5120490846383245, -2.6794768245183382, -2.8335739517133156,
                    -3.04091873529656, -1.9092800808448582, -2.200390738615807,
                    -2.2355793278944853, -3.2208640309677152, -2.692415995640765,
                    -2.695964030654509, -2.523150350743638, -3.0240293434017445,
                    -2.926735479029458, -1.1896484077345144, -2.3473701165668723,
                    -1.807060894179753, -1.906728095483453, -2.2734711093640767,
                    -2.906080789804657, -3.1262641923373566],
              'yaxis': 'y'},
             {'marker': {'color': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
                                   14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
                                   26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
                                   38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
                                   50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
                                   62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
                                   74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
                                   86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
                                   98, 99, 100, 101, 102, 103, 104, 105, 106, 107,
                                   108, 109, 110, 111, 112, 113, 114, 115, 116,
                                   117, 118, 119, 120, 121, 122, 123, 124, 125,
                                   126, 127, 128, 129, 130, 131, 132, 133, 134,
                                   135, 136, 137, 138, 139, 140, 141, 142, 143,
                                   144, 145, 146, 147, 148, 149, 150, 151, 152,
                                   153, 154, 155, 156, 157, 158, 159, 160, 161,
                                   162, 163, 164, 165, 166, 167, 168, 169, 170,
                                   171, 172, 173, 174, 175, 176, 177, 178, 179,
                                   180, 181, 182, 183, 184, 185, 186, 187, 188,
                                   189, 190, 191, 192, 193, 194, 195, 196, 197,
                                   198, 199],
                         'colorbar': {'title': {'text': 'Trial'}, 'x': 1.0, 'xpad': 40},
                         'colorscale': [[0.0, 'rgb(247,251,255)'], [0.125,
                                        'rgb(222,235,247)'], [0.25,
                                        'rgb(198,219,239)'], [0.375,
                                        'rgb(158,202,225)'], [0.5,
                                        'rgb(107,174,214)'], [0.625,
                                        'rgb(66,146,198)'], [0.75,
                                        'rgb(33,113,181)'], [0.875,
                                        'rgb(8,81,156)'], [1.0, 'rgb(8,48,107)']],
                         'line': {'color': 'Grey', 'width': 0.5},
                         'showscale': False},
              'mode': 'markers',
              'name': 'Feasible Trial',
              'showlegend': False,
              'type': 'scatter',
              'x': [20, 28, 32, 6, 10, 12, 17, 6, 26, 15, 30, 17, 25, 30, 11, 12,
                    26, 7, 24, 4, 3, 21, 23, 16, 4, 17, 25, 6, 28, 18, 4, 28, 8,
                    11, 32, 10, 17, 8, 8, 24, 18, 6, 1, 6, 5, 29, 18, 29, 12, 25,
                    29, 22, 23, 8, 28, 12, 13, 17, 24, 6, 12, 31, 13, 18, 4, 17,
                    23, 26, 17, 26, 4, 18, 2, 17, 3, 21, 11, 3, 23, 9, 9, 20, 25,
                    2, 4, 14, 2, 28, 21, 19, 18, 29, 1, 11, 10, 29, 6, 14, 30, 25,
                    27, 1, 31, 15, 25, 16, 29, 25, 23, 3, 12, 25, 18, 16, 4, 19,
                    28, 32, 32, 17, 21, 9, 20, 12, 32, 27, 27, 14, 1, 5, 27, 9, 32,
                    31, 5, 22, 22, 28, 13, 20, 1, 14, 26, 31, 9, 11, 5, 21, 16, 2,
                    3, 12, 26, 30, 24, 16, 24, 29, 15, 13, 11, 22, 18, 5, 19, 8, 6,
                    29, 32, 28, 22, 9, 14, 20, 16, 5, 26, 20, 30, 24, 24, 26, 27,
                    29, 13, 17, 18, 31, 26, 26, 24, 29, 28, 5, 21, 12, 13, 19, 28,
                    30],
              'xaxis': 'x2',
              'y': [-2.3128756957884375, -2.8993306860968433, -3.3568205475025734,
                    -1.0176866156267157, -1.5669691458421142, -1.7883669216794122,
                    -2.2053409915133995, -1.1254780626668444, -2.6824297859660917,
                    -2.071032034206092, -3.1807387437168035, -2.1921665587526635,
                    -2.577343200387279, -3.1471609934276, -1.7006350161760817,
                    -1.8425294001889134, -2.693191592262025, -1.3889542689178322,
                    -2.5346898325732203, -0.6660948652516652, -0.5296664030492806,
                    -2.3508100199373603, -2.465671331775366, -2.143425354751674,
                    -0.5709544932289036, -2.2074416949301, -2.5802212927169954,
                    -1.0301876597534563, -2.925206453736279, -2.2268212565758154,
                    -0.6225761184710048, -2.9115099636693387, -1.3625736558780772,
                    -1.810340346456048, -3.3523231599578294, -1.5657939007866286,
                    -2.188155543661646, -1.530066336685871, -1.6074554873086249,
                    -2.5158744185747643, -2.241779832351988, -1.0390632499468082,
                    -0.9629405900464441, -1.1794301624776573, -1.3937481048123614,
                    -3.038713020034084, -2.236501628392813, -3.0353554409724604,
                    -1.8010260228852792, -2.595166012223089, -3.006959668258182,
                    -2.4065531628209635, -2.4554143280678415, -1.4630064533113787,
                    -2.902748533378481, -1.7902830321106087, -1.9592935172015626,
                    -2.1914533849447535, -2.5161477847790747, -1.1923667012486938,
                    -1.8617441033853783, -3.2697581468195898, -1.9083223112943712,
                    -2.2317737131218505, -0.8399742635091106, -2.185510785101031,
                    -2.4469003369094176, -2.666965226488302, -2.193954253028522,
                    -2.6760193437573343, -0.6547487329802154, -2.228104629021839,
                    -0.27183606800868343, -2.1889300243143586, -0.8591296606597997,
                    -2.3533919714955274, -1.6759983070237214, -0.6134275065916114,
                    -2.4332333152474934, -1.469049387809039, -1.5137941754484534,
                    -2.3161198091330446, -2.59456974904458, -0.26352476362981275,
                    -0.7421531662038978, -2.00513380195364, -0.8427268317379859,
                    -2.9231762087728677, -2.350387522284133, -2.2509942898288045,
                    -2.223581179189172, -3.028823093266374, -0.24485454519965763,
                    -1.6930969077927465, -1.6750422562880931, -3.0247015593614703,
                    -1.015066012294838, -2.0477093090891514, -3.150280877727666,
                    -2.587547912579123, -2.820623780010463, -0.5298470007596979,
                    -3.2425438952089545, -2.0795106199841884, -2.5907253425018615,
                    -2.160678587039768, -3.0065741170755933, -2.5835594603788055,
                    -2.4603992258713676, -0.9829478865864157, -1.8207414419377492,
                    -2.5852111250818703, -2.2293676616346363, -2.1479511782043272,
                    -0.5668757653396618, -2.2474862457025067, -2.9224135794266117,
                    -3.365933482315209, -3.3249070703943375, -2.1836080580542854,
                    -2.353379488934982, -1.462711405710093, -2.3107443228844664,
                    -1.800290082328474, -3.335376493225108, -2.8036771045532918,
                    -2.779894967188965, -2.0024974865249474, -0.2038525021397634,
                    -1.465001486804055, -2.7758022639190494, -1.4585832507255319,
                    -3.295774380908251, -3.2408927363321616, -0.8578802358306936,
                    -2.3954422100387385, -2.39325823880122, -2.905578201054804,
                    -1.9342137350264916, -2.317884862980963, -0.27727779640208544,
                    -1.9992616855988132, -2.6795987764171145, -3.2357251966278513,
                    -1.4637878115619352, -1.6670984608550707, -0.7992279675611433,
                    -2.3596563065702854, -2.1384243116130013, -0.33511848159123053,
                    -0.41615902587262577, -1.795628394152919, -2.6947559437949,
                    -3.1421130503657393, -2.5582494912720914, -2.1369807652177344,
                    -2.519898800683006, -3.0308211050433225, -2.0893269672050123,
                    -1.920904104945702, -1.6822873776177132, -2.4305231436367665,
                    -2.231958740771789, -0.8678812923018986, -2.26565038095684,
                    -1.3746844062589028, -1.005357183894338, -3.0157597102354456,
                    -3.3562455056565526, -2.9221784787364187, -2.399710886972611,
                    -1.475633466587687, -2.000946871738448, -2.310963217044788,
                    -2.1271386767405533, -0.8170217416728509, -2.7096866196333926,
                    -2.305861359679968, -3.129365296348909, -2.5048735185050943,
                    -2.5120490846383245, -2.6794768245183382, -2.8335739517133156,
                    -3.04091873529656, -1.9092800808448582, -2.200390738615807,
                    -2.2355793278944853, -3.2208640309677152, -2.692415995640765,
                    -2.695964030654509, -2.523150350743638, -3.0240293434017445,
                    -2.926735479029458, -1.1896484077345144, -2.3473701165668723,
                    -1.807060894179753, -1.906728095483453, -2.2734711093640767,
                    -2.906080789804657, -3.1262641923373566],
              'yaxis': 'y2'},
             {'marker': {'color': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
                                   14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
                                   26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
                                   38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
                                   50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
                                   62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
                                   74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
                                   86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
                                   98, 99, 100, 101, 102, 103, 104, 105, 106, 107,
                                   108, 109, 110, 111, 112, 113, 114, 115, 116,
                                   117, 118, 119, 120, 121, 122, 123, 124, 125,
                                   126, 127, 128, 129, 130, 131, 132, 133, 134,
                                   135, 136, 137, 138, 139, 140, 141, 142, 143,
                                   144, 145, 146, 147, 148, 149, 150, 151, 152,
                                   153, 154, 155, 156, 157, 158, 159, 160, 161,
                                   162, 163, 164, 165, 166, 167, 168, 169, 170,
                                   171, 172, 173, 174, 175, 176, 177, 178, 179,
                                   180, 181, 182, 183, 184, 185, 186, 187, 188,
                                   189, 190, 191, 192, 193, 194, 195, 196, 197,
                                   198, 199],
                         'colorbar': {'title': {'text': 'Trial'}, 'x': 1.0, 'xpad': 40},
                         'colorscale': [[0.0, 'rgb(247,251,255)'], [0.125,
                                        'rgb(222,235,247)'], [0.25,

In [56]:
optuna.visualization.plot_param_importances(study)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'cliponaxis': False,
              'hovertemplate': [max_depth (IntDistribution):
                                5.872648154647039e-05<extra></extra>, n_estimators
                                (IntDistribution):
                                8.313489294584116e-05<extra></extra>,
                                min_samples_split (IntDistribution):
                                0.002992332396614846<extra></extra>,
                                min_samples_leaf (IntDistribution):
                                0.996865806228893<extra></extra>],
              'name': 'Objective Value',
              'orientation': 'h',
              'text': [<0.01, <0.01, <0.01, 1.00],
              'textposition': 'outside',
              'type': 'bar',
              'x': [5.872648154647039e-05, 8.313489294584116e-05,
                    0.002992332396614846, 0.996865806228893],
              'y': [max_depth, n_estimators, min_samples_split, min_samples_leaf]}],
    'layout': {'template': '...',
               'title': {'text': 'Hyperparameter Importances'},
               'xaxis': {'title': {'text': 'Hyperparameter Importance'}},
               'yaxis': {'title': {'text': 'Hyperparameter'}}}
})

In [57]:
best_n_estimators = best_params['n_estimators']
best_max_depth = best_params['max_depth']
best_min_samples_split = best_params['min_samples_split']
best_min_samples_leaf = best_params['min_samples_leaf']

In [58]:
best_model = RandomForestRegressor(n_estimators=best_n_estimators, max_depth=best_max_depth, min_samples_split=best_min_samples_split, min_samples_leaf=best_min_samples_leaf)
best_model.fit(X_train, y_train)
y_pred = best_model.predict(X_test)

In [60]:
mean_absolute_error(y_test, y_pred)

0.3230935517791243

In [61]:
mean_squared_error(y_test, y_pred)

0.16319614849404615

In [62]:
r2_score(y_test, y_pred)

0.9827934125881214